export * as day1 from './day1' 
export * as day2 from './day2' 
export * as day3 from './day3' 
export * as day4 from './day4' 
export * as day5 from './day5' 
export * as day6 from './day6' 
export * as day7 from './day7' 